version: "3.8"

services:

  db:
    image: mysql
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    entrypoint: ./scripts/entrypoint.sh

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker_scraping:
    build: .
    depends_on:
      - db
      - redis
      - web
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: celery -A main_celery.celery worker -Q scraping_queue

  celery_worker_diagrams:
    build: .
    depends_on:
      - db
      - redis
      - web
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: celery -A main_celery.celery worker -Q diagrams_queue

  celery_beat:
    build: .
    depends_on:
      - db
      - redis
      - web
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: celery -A main_celery.celery beat --loglevel=INFO

#  flower:
#    image: mher/flower
#    ports:
#      - "5555:5555"
#    depends_on:
#      - celery_worker
#    command: ["--broker", "redis://redis:6379", "--port=5555"]
volumes:
  mysql_data:
