"""Create model DiagramFileMetaData

Revision ID: 9754a26eabb7
Revises: 
Create Date: 2024-07-05 11:42:59.671373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9754a26eabb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DiagramFileMetaData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DiagramFileMetaData_file_name'), 'DiagramFileMetaData', ['file_name'], unique=True)
    op.create_index(op.f('ix_DiagramFileMetaData_id'), 'DiagramFileMetaData', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DiagramFileMetaData_id'), table_name='DiagramFileMetaData')
    op.drop_index(op.f('ix_DiagramFileMetaData_file_name'), table_name='DiagramFileMetaData')
    op.drop_table('DiagramFileMetaData')
    # ### end Alembic commands ###
