"""Create table DiagramFileMetaData  and ScrapingResultFileMetaData

Revision ID: 82d86ce70ba2
Revises: 
Create Date: 2024-07-07 13:52:01.281495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d86ce70ba2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagram_file_meta_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('diagram_type', sa.Enum('employment_type', 'location', 'optional_skills', 'required_skills', 'o_s', 'skills_by_level_of_exp', 'ua_support', name='diagramtypes'), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagram_file_meta_data_diagram_type'), 'diagram_file_meta_data', ['diagram_type'], unique=False)
    op.create_index(op.f('ix_diagram_file_meta_data_file_name'), 'diagram_file_meta_data', ['file_name'], unique=True)
    op.create_table('scraping_result_file_meta_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_result_file_meta_data_file_name'), 'scraping_result_file_meta_data', ['file_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraping_result_file_meta_data_file_name'), table_name='scraping_result_file_meta_data')
    op.drop_table('scraping_result_file_meta_data')
    op.drop_index(op.f('ix_diagram_file_meta_data_file_name'), table_name='diagram_file_meta_data')
    op.drop_index(op.f('ix_diagram_file_meta_data_diagram_type'), table_name='diagram_file_meta_data')
    op.drop_table('diagram_file_meta_data')
    # ### end Alembic commands ###
