"""Create table DiagramFileMetaData  and ScrapingResultFileMetaData

Revision ID: c09617cc24ab
Revises: 
Create Date: 2024-07-09 21:48:30.785391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09617cc24ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraping_result_file_meta_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_result_file_meta_data_file_name'), 'scraping_result_file_meta_data', ['file_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraping_result_file_meta_data_file_name'), table_name='scraping_result_file_meta_data')
    op.drop_table('scraping_result_file_meta_data')
    # ### end Alembic commands ###
